[package]
name = "snapbox-macros"
version = "0.3.10"
description = "Snapshot testing toolbox"
repository = "https://github.com/assert-rs/trycmd/"
homepage = "https://github.com/assert-rs/trycmd/tree/main/crates/snapbox"
documentation = "http://docs.rs/snapbox/"
readme = "README.md"
categories = ["development-tools::testing"]
keywords = ["cli", "test", "assert", "command"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = []
color = ["dep:anstream"]

## Extra debugging information
debug = []

[dependencies]
anstream = { version = "0.6.7", optional = true }

[lints]
workspace = true
